SIP/2.0 200 OK
Via: SIP/2.0/UDP r9ik7446ccqm.invalid;branch=z9hG4bK5075365
From:  <sip:10000@quitee.com>;tag=kq74oia6ra
To: quitee <sip:bob@example.com>;tag=91b73d8e-06af-4add-872b-d725c7da8bdb
Call-Id: mrvmadori1cu6gm3rusa
CSeq: 8757 INVITE
Content-Type: application/sdp
Content-Length: 193
Contact: quitee<sip:bob@example.com>

v=0
o=- 851017165 1565835106 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 BD:A4:EC:F9:46:9F:17:CC:0F:87:40:A8:C5:0B:DD:2D:0C:3B:B1:CD:69:E7:13:56:97:18:AF:39:B4:92:C4:4A
a=group:BUNDLE